### ISSUE TITLE
Limb length consistency

### ISSUE THREAD

**Issue by aphalak** [DenisTome/Lifting-from-the-Deep-release#2]
I am having success with accurate 2D detections and a 3D model that looks well-posed. 
However upon closer inspections it seems that the left and right limbs differ in size greatly for a single frame. Is this expected behavior, or should I be seeing right-side limbs that are almost similar in size to the left-side limbs?

Also, what is the right way to scale the 3D points to real-word co-ordinates if i know my camera parameters?

**Comment by DenisTome** [comment]
Hi, yes this can happen. The reason is that we are not enforcing any limb length constraint in the reconstruction (the normalisation is just done on the height of the person).

About scaling the 3D points to real-world coordinates, there's the problem that given a pose, you don't know if this is either a tall person standing far from the camera or a short person standing close to the camera. Hence, for doing this you would need to now the height of the person in advance (like a configuration step at the beginning). Alternatively, another way of approaching the problem would be to know the ground plane, and in that case you would be able to compute the distance of the person with respect to the camera.
