### ISSUE TITLE
Requirements 

### ISSUE THREAD

**Issue by myagovki** [DenisTome/Lifting-from-the-Deep-release#22]
Hello!

I would like to know what the minimum requirements on the os are, such as cpu, ram, graphics card...

Thanks!

**Comment by DenisTome** [comment]
We haven't made tests in this regard.
In order just to test the model, I think the Nvidia 1080ti is already too much, you could potentially have something less powerful; for the RAM something like 16 GB
An alternative is to run the code in CPU mode rather than GPU mode, but the execution time is going to be significantly larger.
