### ISSUE TITLE
Zero-size array error when running on some images

### ISSUE THREAD

**Issue by GeorgianaPetria** [DenisTome/Lifting-from-the-Deep-release#3]
I've used it on several images and, while some work perfectly, there are a couple of them that trigger a very weird error. Do you know why this might happen and how to fix this issue?

File "demo.py", line 67, in <module>

    pose3D = poseLifting.compute_3d(pose2D, weights)

    File "/home/ubuntu/projects/Lifting-from-the-Deep-release/utils/prob_model.py", line 219, in compute_3d

    norm_pose, _ = Prob3dPose.normalise_data(reg_joints, weights)

    File "/home/ubuntu/projects/Lifting-from-the-Deep-release/utils/prob_model.py", line 100, in normalise_data

    m2 = d2[:, 1, idx_consider].min(1) / 2.0

    File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 29, in _amin

    return umr_minimum(a, axis, None, out, keepdims)

    ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by DenisTome** [comment]
The problem is related to zero visible joints detected in 2D.
Changing the file utils/config.py and specifically the variable VISIBLE_PART can produce more 2D predictions (with more uncertainty though).
I've added some controls in the code for which if the number of 2D joints is insufficient then it triggers and error (see [commit](https://github.com/DenisTome/Lifting-from-the-Deep-release/commit/446940b422a2350caf601c78062e0fadcd45bde6)
