### ISSUE TITLE
Limitation on input image ? and input to 3d filter

### ISSUE THREAD

**Issue by basicvisual** [DenisTome/Lifting-from-the-Deep-release#40]
Hi 
I had been reading , that the reason why it is very slow , is the fact the 2D , detections take the most of the time 
[issue stated here](https://github.com/DenisTome/Lifting-from-the-Deep-release/issues/13#issuecomment-344623023). Could you point , where one can change the input to for other 2D detectors to work ? 

My second question , is that is there some limitation on the input picture ? It seems for some of the pictures it seem to lifiting perfectly and sometimes it returns an error 

```
`Traceback (most recent call last):
  File "demo_modify.py", line 67, in <module>
    sys.exit(main())
  File "demo_modify.py", line 31, in main
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # conversion to rgb
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

```

**Comment by DenisTome** [comment]
Hi, yes that is correct.

If you check here: packages/lifting/_pose_estimator.py, line 144 takes the 2D pose estimated by the first module and lifts them in 3D. You can replace the 2D pose detector with whatever you prefer, making sure that the pose you get has the same set of joints as expected by our approach, and it should work.

About the second point, that's unusual.
cv2 is a very common library and very stable. Based on that, I would say that the the only reason it is not working is because image is None (not being loaded). Make sure that the path is correct.

I'm going to close this.
Feel free the re-open it in case there's an issue with this project's code

**Comment by basicvisual** [comment]
Thank you for your quick response. I think 2D detections from posenet will not work because it returns a `17x2` array and i think your case when i do a dump of the values its `14x2`
