### ISSUE TITLE
problem about person with no face in images

### ISSUE THREAD

**Issue by Angel113110** [DenisTome/Lifting-from-the-Deep-release#50]
Hi, author
    I didn't explain my problem clearly before. The problem I face now is when I test my images, some of them are person with no face , that is back to the camera. In this situation, the model cannot detect person in images. Can model solve this problem? Thanks!

**Comment by DenisTome** [comment]
Yes, the model should work even when the face of the person is not visible.
If this is currently not working, then it's probably related to the thresholds which you can find in the config file config.py

VISIBLE_PART = 1e-3
MIN_NUM_JOINTS = 5
CENTER_TR = 0.4

**Comment by Angel113110** [comment]
Hi, author
  I should change all of three thresholds values? How to change? Which direction? Bigger or smaller?

**Comment by DenisTome** [comment]
Min number of joints refers to the minimum number of joints that need to have small uncertainty in order to show the skeleton. Keep that to 5.
CENTER_TR is the maximum amount of uncertainty required to consider a person visible. Reduce it if the person is not found.
VISIBLE_PART is similar to CENTER_TR for the joints. Similarly, reduce that value if not enough joints are found.

**Comment by Angel113110** [comment]
Hi, author
    I tried to change these values. But when I change smaller values. It seemed that everything was wrong. I only got a picture which contained many mess points and lines. How it happened?

**Comment by DenisTome** [comment]
If that happens it's because the pose cannot be identified reliably for that kind of image.
It could be that the size of the image or the conditions (like noise) is such that the model cannot retrieve the correct information.
